name = "heidelberger"
description = ""
version = "0.1.0-dev"

authors = ["Jesper Quorning"]
maintainers = ["Jesper Quorning <jesper.quorning@gmail.com>"]
maintainers-logins = ["jquorning"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["heidelberger"]

[test]
runner = "alire"

[[depends-on]]
aws = "=24"
xmlada = "^24.0.0"
gnatcoll = "^24.0.0"
simple_components = "^4.68.0"
